# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}: let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name
    {
      nativeBuildInputs = [zig];
    }
    ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
  }: let
    parts = lib.splitString "#" url;
    url_base = builtins.elemAt parts 0;
    url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
    rev_base = builtins.elemAt parts 1;
    rev =
      if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null
      then rev_base
      else "refs/heads/${rev_base}";
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
  }: let
    parts = lib.splitString "://" url;
    proto = builtins.elemAt parts 0;
    path = builtins.elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig {
        inherit name hash;
        url = "http://${path}";
      };
      "git+https" = fetchGitZig {
        inherit name hash;
        url = "https://${path}";
      };
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "clipboard-0.1.0-4y-6fXgjAAAG9lcF33e0cBPUg-ynG3L6vvPYgei-gokt";
      path = fetchZigArtifact {
        name = "clipboard";
        url = "git+https://github.com/dgv/clipboard#0ba2e06f3ade58237a45c4f3321884dee2aba775";
        hash = "sha256-WmVQhWNKWo7wuird60RlItfU1ItYjKn63KPKkac29G8=";
      };
    }
    {
      name = "sqlite-3.48.0-F2R_a5yODgDFvwwsytm7ZONcSqYBo3qv1PmXOtw3tqLA";
      path = fetchZigArtifact {
        name = "sqlite";
        url = "git+https://github.com/vrischmann/zig-sqlite#6d90ee900d186a7fbb6066f28ee13beeaf8be345";
        hash = "sha256-6RxaQO+EAZzuj63m35WV+ofza2VlCHbeDWPa/mjtRDE=";
      };
    }
    {
      name = "N-V-__8AAH-mpwB7g3MnqYU-ooUBF1t99RP27dZ9addtMVXD";
      path = fetchZigArtifact {
        name = "sqlite";
        url = "https://www.sqlite.org/2025/sqlite-amalgamation-3490200.zip";
        hash = "sha256-kh/HJVF6aU333ziio9/t5mhAJLV4jZ3kZBh8YSr7WRg=";
      };
    }
    {
      name = "zeit-0.6.0-5I6bk4t8AgCP0UGGHVF_khlmWZkAF5XtfQWEKCyLoptU";
      path = fetchZigArtifact {
        name = "zeit";
        url = "git+https://github.com/rockorager/zeit#74be5a2afb346b2a6a6349abbb609e89ec7e65a6";
        hash = "sha256-bydKtoH7XEDIu0JcTsVCa7ewdPAFfgf2bLOUKO63Aok=";
      };
    }
  ]
